CREATE DATABASE KAVYA;
SHOW DATABASES;
USE KAVYA;
SHOW TABLES;
--------DDL 
---CREATE
CREATE TABLE STUDENT1 (SID INT,SNAME VARCHAR(10),SBRANCH CHAR(3),SPHN INT
DESC STUDENT1;

----ALTER
ALTER TABLE STUDENT1 ADD SADDRESS VARCHAR(50);
DESC STUDENT1;
---ALTER DROP
ALTER TABLE STUDENT1 DROP COLUMN SADDRESS;
---ALTER MODIFY
ALTER TABLE STUDENT1 MODIFY COLUMN SBRANCH VARCHAR(10);
DESC STUDENT1;

---DROP
DROP TABLE STUDENT1;
DESC STUDENT1;
CREATE TABLE STUDENT1 (SID INT,SNAME VARCHAR(10),SBRANCH CHAR(3),SPHN INT);
ALTER TABLE STUDENT1 MODIFY COLUMN SPHN BIGINT;

----DML
--INSERT
INSERT INTO STUDENT1 VALUES(1,"KAVYA","CSE",9876543210);
INSERT INTO STUDENT1 VALUES(2,"ANJALI","CSE",876543291),(3,"JESH","ECE",912341234);
INSERT INTO STUDENT1 (SID,SNAME,SBRANCH) VALUES(4,"MEGHANA","ECE");
INSERT INTO STUDENT1 (SID,SNAME,SBRANCH) VALUES(5,"SAI","EEE"),(6,"VARDHAN","ECE");
SELECT *FROM STUDENT1; 
SELECT SNAME,SBRANCH FROM STUDENT1;

---UPDATE
SET SQL_SAFE_UPDATES=0;
UPDATE STUDENT1 SET SID=100 WHERE SBRANCH="CSE";